# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dasboard_kasir.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from form_penjualan import Ui_Dialog as Ui_FormPenjualan
from riwayat_penjualan import RiwayatPenjualan
from PyQt5 import QtCore, QtGui, QtWidgets

# --- CLASS UI GENERATED (TIDAK DIUBAH) ---
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 20, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 60, 251, 41))
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 120, 251, 41))
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 260, 93, 28))
        self.pushButton_4.setStyleSheet("background-color: #ffcccc; color: red;")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dashboard Kasir"))
        self.label.setText(_translate("Dialog", "DASHBOARD KASIR"))
        self.pushButton.setText(_translate("Dialog", "Jual Kendaraan"))
        self.pushButton_2.setText(_translate("Dialog", "Riwayat Penjualan"))
        self.pushButton_4.setText(_translate("Dialog", "Logout"))

# --- CLASS LOGIC (WRAPPER) ---
class DashboardKasirForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        
        # Connect Tombol
        self.ui.pushButton.clicked.connect(self.buka_form_jual)
        self.ui.pushButton_2.clicked.connect(self.buka_riwayat)
        self.ui.pushButton_4.clicked.connect(self.aksi_logout)

    def buka_form_jual(self):
        self.window_jual = QtWidgets.QWidget()
        self.ui_jual = Ui_FormPenjualan()
        self.ui_jual.setupUi(self.window_jual)
        self.window_jual.show()

    def buka_riwayat(self):
        self.window_riwayat = RiwayatPenjualan()
        self.window_riwayat.show()

    def aksi_logout(self):
        # Saat logout, tutup window ini
        self.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = DashboardKasirForm()
    window.show()
    sys.exit(app.exec_())