# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

import sys
from form_insert_user import InsertUserForm
from form_edit_user import EditUserForm
from form_delete_user import DeleteUserForm
from form_view_user import ViewUserForm
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# =================================================================
# IMPORT FORM LAIN (Pastikan file-file ini ada di folder yang sama)
# =================================================================


# =================================================================
# 1. BAGIAN TAMPILAN UI (JANGAN DIUBAH - SESUAI DESAIN KAMU)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        
        # Label Judul
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 50, 500, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Tombol Insert
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 150, 300, 50))
        self.pushButton.setObjectName("pushButton")
        
        # Tombol Update
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 220, 300, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        
        # Tombol Delete
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 290, 300, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        
        # Tombol View (Lihat)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 360, 300, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        
        # Tombol Logout
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 220, 200, 150))
        self.pushButton_5.setObjectName("pushButton_5")
        # Kasih warna merah biar beda
        self.pushButton_5.setStyleSheet("background-color: #ffcccc; color: red; font-weight: bold; font-size: 14px;")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dashboard Admin"))
        self.label.setText(_translate("Dialog", "DASHBOARD ADMIN"))
        self.pushButton.setText(_translate("Dialog", "Insert Data User"))
        self.pushButton_4.setText(_translate("Dialog", "Update Data User"))
        self.pushButton_3.setText(_translate("Dialog", "Delete Data User"))
        self.pushButton_2.setText(_translate("Dialog", "Lihat Data User"))
        self.pushButton_5.setText(_translate("Dialog", "Logout"))

# =================================================================
# 2. BAGIAN LOGIKA (CONTROLLER) - DIGABUNG DI SINI
# =================================================================
class DashboardAdminForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        # Panggil UI
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        
        # Hubungkan Tombol ke Fungsi
        self.ui.pushButton.clicked.connect(self.buka_insert)   # Insert
        self.ui.pushButton_4.clicked.connect(self.buka_update) # Update
        self.ui.pushButton_3.clicked.connect(self.buka_delete) # Delete
        self.ui.pushButton_2.clicked.connect(self.buka_view)   # View
        self.ui.pushButton_5.clicked.connect(self.aksi_logout) # Logout

    def buka_insert(self):
        try:
            self.form_insert = InsertUserForm()
            self.form_insert.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form Insert belum diimport/dibuat.")

    def buka_update(self):
        try:
            self.form_update = EditUserForm()
            self.form_update.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form Edit belum diimport/dibuat.")

    def buka_delete(self):
        try:
            self.form_delete = DeleteUserForm()
            self.form_delete.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form Delete belum diimport/dibuat.")

    def buka_view(self):
        try:
            self.form_view = ViewUserForm()
            self.form_view.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form View belum diimport/dibuat.")

    def aksi_logout(self):
        tanya = QMessageBox.question(
            self, "Konfirmasi", "Yakin ingin Logout?",
            QMessageBox.Yes | QMessageBox.No
        )
        if tanya == QMessageBox.Yes:
            self.close()
            # Di sini nanti bisa tambahkan kode untuk kembali ke Login Window

# =================================================================
# 3. JALANKAN APLIKASI
# =================================================================
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = DashboardAdminForm()
    window.show()
    sys.exit(app.exec_())