# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_gudang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-
import mysql.connector
import sys
from form_insert_barang import InsertBarangForm
from form_edit_barang import EditBarangForm
from form_delete_barang import DeleteBarangForm
from form_view_barang import ViewBarangForm
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# =================================================================
# IMPORT FORM BARANG
# =================================================================

# =================================================================
# 1. BAGIAN TAMPILAN UI (SUDAH DIRAPIKAN)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 450) # Ukuran window diperpanjang agar muat dan lega
        
        # --- JUDUL ---
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # --- TOMBOL INSERT ---
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 90, 240, 45))
        self.pushButton.setObjectName("pushButton")
        
        # --- TOMBOL UPDATE ---
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 150, 240, 45))
        self.pushButton_4.setObjectName("pushButton_4")
        
        # --- TOMBOL DELETE ---
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 210, 240, 45))
        self.pushButton_3.setObjectName("pushButton_3")
        
        # --- TOMBOL VIEW ---
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 270, 240, 45))
        self.pushButton_2.setObjectName("pushButton_2")
        
        # --- TOMBOL LOGOUT ---
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 350, 240, 45))
        self.pushButton_5.setObjectName("pushButton_5")
        # Style Merah untuk Logout
        self.pushButton_5.setStyleSheet("""
            QPushButton {
                background-color: #ffcccc; 
                color: red; 
                font-weight: bold; 
                border-radius: 5px;
                border: 1px solid red;
            }
            QPushButton:hover {
                background-color: #ffaaaa;
            }
        """)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dashboard Gudang"))
        self.label.setText(_translate("Dialog", "DASHBOARD GUDANG"))
        self.pushButton.setText(_translate("Dialog", "1. Tambah Barang"))
        self.pushButton_4.setText(_translate("Dialog", "2. Update Barang"))
        self.pushButton_3.setText(_translate("Dialog", "3. Hapus Barang"))
        self.pushButton_2.setText(_translate("Dialog", "4. Lihat Semua Barang"))
        self.pushButton_5.setText(_translate("Dialog", "Logout / Keluar"))

# =================================================================
# 2. BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class DashboardGudangForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        
        # Hubungkan Tombol
        self.ui.pushButton.clicked.connect(self.buka_insert)
        self.ui.pushButton_4.clicked.connect(self.buka_update)
        self.ui.pushButton_3.clicked.connect(self.buka_delete)
        self.ui.pushButton_2.clicked.connect(self.buka_view)
        self.ui.pushButton_5.clicked.connect(self.aksi_logout)

    def buka_insert(self):
        try:
            self.form_insert = InsertBarangForm()
            self.form_insert.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form Insert belum diimport.")

    def buka_update(self):
        try:
            self.form_update = EditBarangForm()
            self.form_update.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form Edit belum diimport.")

    def buka_delete(self):
        try:
            self.form_delete = DeleteBarangForm()
            self.form_delete.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form Delete belum diimport.")

    def buka_view(self):
        try:
            self.form_view = ViewBarangForm()
            self.form_view.exec_()
        except NameError:
            QMessageBox.critical(self, "Error", "Form View belum diimport.")

    def aksi_logout(self):
        tanya = QMessageBox.question(
            self, "Konfirmasi", "Yakin ingin keluar dari sistem gudang?",
            QMessageBox.Yes | QMessageBox.No
        )
        if tanya == QMessageBox.Yes:
            self.close()

# =================================================================
# 3. JALANKAN APLIKASI
# =================================================================
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = DashboardGudangForm()
    window.show()
    sys.exit(app.exec_())