# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_insert_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

import sys
import warnings
warnings.filterwarnings("ignore")

# Import Backend
from mobil import Mobil, Mobil_Sport, Mobil_Listrik 
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


# =================================================================
# 1. BAGIAN UI (TATA LETAK DIRAPIKAN)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 420) # Diperpanjang ke bawah
        
        # --- JUDUL ---
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Font standar untuk label isian
        font_label = QtGui.QFont()
        font_label.setPointSize(8)

        # --- BARIS 1: KATEGORI ---
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 80, 25))
        self.label_6.setFont(font_label)
        self.label_6.setObjectName("label_6")
        
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 80, 230, 25))
        self.comboBox.setObjectName("comboBox")
        
        # --- BARIS 2: MERK ---
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 80, 25))
        self.label_3.setFont(font_label)
        self.label_3.setObjectName("label_3")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 120, 230, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")

        # --- BARIS 3: STOK ---
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 80, 25))
        self.label_4.setFont(font_label)
        self.label_4.setObjectName("label_4")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 160, 230, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")

        # --- BARIS 4: HARGA ---
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 80, 25))
        self.label_5.setFont(font_label)
        self.label_5.setObjectName("label_5")
        
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 200, 230, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")

        # --- BARIS 5: SPESIFIKASI KHUSUS ---
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 240, 90, 25))
        self.label_2.setFont(font_label)
        self.label_2.setObjectName("label_2")
        
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 240, 230, 25))
        self.lineEdit.setObjectName("lineEdit")

        # --- TOMBOL SIMPAN ---
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 320, 200, 45))
        self.pushButton.setObjectName("pushButton")
        
        # Style Tombol Hijau
        self.pushButton.setStyleSheet("""
            QPushButton {
                background-color: #28a745; 
                color: white; 
                font-weight: bold; 
                font-size: 14px;
                border-radius: 5px;
            }
            QPushButton:hover {
                background-color: #218838;
            }
        """)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tambah Barang"))
        self.label.setText(_translate("Dialog", "INPUT DATA MOBIL"))
        self.label_6.setText(_translate("Dialog", "Kategori"))
        self.label_3.setText(_translate("Dialog", "Merk"))
        self.label_4.setText(_translate("Dialog", "Stok"))
        self.label_5.setText(_translate("Dialog", "Harga"))
        self.label_2.setText(_translate("Dialog", "Spesifikasi")) 
        self.pushButton.setText(_translate("Dialog", "SIMPAN DATA"))


# =================================================================
# 2. BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class InsertBarangForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.setup_logika()

    def setup_logika(self):
        # Tambahkan 3 Pilihan: Umum, Sport, Listrik
        self.ui.comboBox.clear()
        self.ui.comboBox.addItems(["Mobil Umum", "Mobil Sport", "Mobil Listrik"])
        
        # Event Listener
        self.ui.comboBox.currentIndexChanged.connect(self.update_tampilan)
        self.ui.pushButton.clicked.connect(self.simpan_ke_database)
        
        # Panggil sekali di awal
        self.update_tampilan()

    def update_tampilan(self):
        kategori = self.ui.comboBox.currentText()
        if kategori == "Mobil Umum":
            self.ui.label_2.setText("Spesifikasi ")
            self.ui.lineEdit.setPlaceholderText("Tidak perlu diisi")
            self.ui.lineEdit.setEnabled(False) # Disable input
            self.ui.lineEdit.setStyleSheet("background-color: #f0f0f0;") # Warna abu-abu
        elif kategori == "Mobil Sport":
            self.ui.label_2.setText("Kecepatan")
            self.ui.lineEdit.setPlaceholderText("Contoh: 350 (km/h)")
            self.ui.lineEdit.setEnabled(True)
            self.ui.lineEdit.setStyleSheet("background-color: white;")
        else: # Listrik
            self.ui.label_2.setText("Kapasitas")
            self.ui.lineEdit.setPlaceholderText("Contoh: 75 (kWh)")
            self.ui.lineEdit.setEnabled(True)
            self.ui.lineEdit.setStyleSheet("background-color: white;")

    def simpan_ke_database(self):
        merk = self.ui.lineEdit_2.text()
        stok = self.ui.lineEdit_3.text()
        harga = self.ui.lineEdit_4.text()
        kategori = self.ui.comboBox.currentText()
        
        # Validasi Umum
        if not all([merk, stok, harga]):
            QMessageBox.warning(self, "Peringatan", "Merk, Stok, dan Harga harus diisi!")
            return

        try:
            harga_int = int(harga)
            stok_int = int(stok)

            if kategori == "Mobil Umum":
                mobil = Mobil(merk, harga_int, stok_int)
                mobil.simpan()
                info = f"✅ Mobil Umum '{merk}' tersimpan!"

            elif kategori == "Mobil Sport":
                spek = self.ui.lineEdit.text()
                if not spek:
                    QMessageBox.warning(self, "Info", "Kecepatan harus diisi!")
                    return
                mobil = Mobil_Sport(merk, harga_int, stok_int, int(spek))
                mobil.simpan()
                info = f"🏎️ Mobil Sport '{merk}' tersimpan!"

            elif kategori == "Mobil Listrik":
                spek = self.ui.lineEdit.text()
                if not spek:
                    QMessageBox.warning(self, "Info", "Kapasitas harus diisi!")
                    return
                mobil = Mobil_Listrik(merk, harga_int, stok_int, int(spek))
                mobil.simpan()
                info = f"🔋 Mobil Listrik '{merk}' tersimpan!"

            QMessageBox.information(self, "Sukses", info)
            self.reset_form()

        except ValueError:
            QMessageBox.warning(self, "Error", "Harga, Stok, dan Spek harus angka!")
        except Exception as e:
            QMessageBox.critical(self, "Error Database", str(e))

    def reset_form(self):
        self.ui.lineEdit_2.clear() # Merk
        self.ui.lineEdit_3.clear() # Stok
        self.ui.lineEdit_4.clear() # Harga
        self.ui.lineEdit.clear()   # Spek
        self.ui.comboBox.setCurrentIndex(0) # Reset ke Mobil Umum

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = InsertBarangForm()
    window.show()
    sys.exit(app.exec_())