# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_view_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

import sys
import warnings
warnings.filterwarnings("ignore")

# Import Backend
from mobil import Mobil
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QHeaderView, QMessageBox


# =================================================================
# 1. BAGIAN UI (TATA LETAK DIRAPIKAN)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        # Memperlebar window agar 6 kolom muat dengan lega
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 450) 
        
        # --- JUDUL ---
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 600, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # --- TABEL ---
        self.tableView = QtWidgets.QTableView(Dialog)
        # Margin kiri-kanan 30px, bawah 30px
        self.tableView.setGeometry(QtCore.QRect(30, 70, 640, 350)) 
        
        # Styling Tabel agar lebih modern (Opsional)
        self.tableView.setAlternatingRowColors(True) # Baris belang-belang
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows) # Pilih satu baris full
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Lihat Data Barang"))
        self.label.setText(_translate("Dialog", "DAFTAR STOK GUDANG"))

# =================================================================
# 2. BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class ViewBarangForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        
        # Load data saat dibuka
        self.load_data_mobil()

    def load_data_mobil(self):
        try:
            # 1. Ambil data dari Backend (Join 3 Tabel)
            data_mobil = Mobil.get_all_mobil()
            
            # 2. Setup Model
            model = QStandardItemModel()
            headers = ['ID', 'Merk', 'Harga', 'Stok', 'Kategori', 'Spesifikasi']
            model.setHorizontalHeaderLabels(headers)

            # 3. Masukkan Data
            for row in data_mobil:
                # row = (id, merk, harga, stok, kecepatan, kapasitas)
                uid, merk, harga, stok, kecepatan, kapasitas = row
                
                # Logic Kategori
                kategori = "Umum"
                spek = "-"
                
                if kecepatan is not None:
                    kategori = "Sport"
                    spek = f"{kecepatan} km/h"
                elif kapasitas is not None:
                    kategori = "Listrik"
                    spek = f"{kapasitas} kWh"

                # Format Rupiah
                harga_fmt = f"Rp {harga:,}".replace(",", ".")

                # Buat Items
                items = [
                    QStandardItem(str(uid)),
                    QStandardItem(merk),
                    QStandardItem(harga_fmt),
                    QStandardItem(str(stok)),
                    QStandardItem(kategori),
                    QStandardItem(spek)
                ]

                # Set Read Only & Alignment
                for i, item in enumerate(items):
                    item.setEditable(False)
                    # ID, Harga, Stok, Kategori rata tengah
                    if i in [0, 2, 3, 4]: 
                        item.setTextAlignment(QtCore.Qt.AlignCenter)
                
                model.appendRow(items)

            # 4. Pasang Model ke View
            self.ui.tableView.setModel(model)
            
            # 5. Atur Lebar Kolom Biar Rapi
            header = self.ui.tableView.horizontalHeader()
            
            # ID kecil saja (Fixed)
            header.setSectionResizeMode(0, QHeaderView.ResizeToContents)
            # Stok & Kategori sesuaikan konten
            header.setSectionResizeMode(3, QHeaderView.ResizeToContents)
            header.setSectionResizeMode(4, QHeaderView.ResizeToContents)
            # Sisanya bagi rata (Stretch)
            header.setSectionResizeMode(1, QHeaderView.Stretch) # Merk
            header.setSectionResizeMode(2, QHeaderView.Stretch) # Harga
            header.setSectionResizeMode(5, QHeaderView.Stretch) # Spek

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Gagal memuat data: {e}")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = ViewBarangForm()
    window.show()
    sys.exit(app.exec_())