# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_edit_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-
import sys
import warnings
warnings.filterwarnings("ignore") # Sembunyikan warning merah
from user import User

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# =================================================================
# BAGIAN UI (JANGAN DIUBAH)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 320) # Sedikit diperbesar
        
        # Judul
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setText("Edit Data User")

        # --- BARIS 1: ID & TOMBOL CARI ---
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 80, 20))
        self.label_2.setText("ID User:") 
        
        # Input ID (lineEdit)
        self.lineEdit = QtWidgets.QLineEdit(Dialog) 
        self.lineEdit.setGeometry(QtCore.QRect(140, 70, 100, 20))
        self.lineEdit.setPlaceholderText("Contoh: 1")

        # Tombol Cari (pushButton_2)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 70, 60, 22))
        self.pushButton_2.setText("Cari")

        # --- BARIS 2: NAMA ---
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 80, 20))
        self.label_3.setText("Nama:")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 110, 170, 20))

        # --- BARIS 3: USERNAME ---
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 80, 20))
        self.label_4.setText("Username:")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 140, 170, 20))

        # --- BARIS 4: PASSWORD ---
        self.label_pw = QtWidgets.QLabel(Dialog)
        self.label_pw.setGeometry(QtCore.QRect(50, 170, 80, 20))
        self.label_pw.setText("Password:")
        # Kita pakai lineEdit_4 buatan sendiri untuk password
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 170, 170, 20))
        self.lineEdit_4.setPlaceholderText("(Kosongkan jika tidak ubah)")

        # --- BARIS 5: POSISI ---
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 200, 80, 20))
        self.label_6.setText("Posisi:")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 200, 170, 22))

        # --- TOMBOL UPDATE ---
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 250, 160, 35))
        self.pushButton.setText("Simpan Perubahan")
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)

# =================================================================
# BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class EditUserForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.current_id = None # Menyimpan ID user yang sedang diedit
        
        # Isi Pilihan Posisi
        self.ui.comboBox.addItems(['admin', 'gudang', 'kasir'])
        
        # Hubungkan Tombol
        self.ui.pushButton_2.clicked.connect(self.aksi_cari)   # Tombol Cari
        self.ui.pushButton.clicked.connect(self.aksi_update)   # Tombol Update

    def aksi_cari(self):
        id_input = self.ui.lineEdit.text().strip()
        if not id_input:
            QMessageBox.warning(self, "Peringatan", "Masukkan ID User dulu!")
            return

        try:
            # Gunakan class User untuk mencari data
            usr = User()
            # method select_user_by_id harus ada di user.py
            data = usr.select_user_by_id(id_input) 
            
            if data:
                # Data ditemukan! (id, name, username, password, posisi)
                self.current_id = data[0]
                self.ui.lineEdit_2.setText(data[1])     # Isi Nama
                self.ui.lineEdit_3.setText(data[2])     # Isi Username
                self.ui.lineEdit_4.setText("")          # Password dikosongkan (keamanan)
                self.ui.comboBox.setCurrentText(data[4])# Pilih Posisi di Combo
                
                QMessageBox.information(self, "Berhasil", f"User '{data[1]}' ditemukan!")
            else:
                QMessageBox.warning(self, "Gagal", f"User dengan ID {id_input} tidak ditemukan.")
                self.reset_form(reset_id=False)
                
        except Exception as e:
            QMessageBox.critical(self, "Error Database", str(e))

    def aksi_update(self):
        if not self.current_id:
            QMessageBox.warning(self, "Peringatan", "Cari User terlebih dahulu!")
            return

        # Ambil data dari inputan
        nama_baru = self.ui.lineEdit_2.text()
        user_baru = self.ui.lineEdit_3.text()
        pass_baru = self.ui.lineEdit_4.text() # Bisa kosong
        posisi_baru = self.ui.comboBox.currentText()

        try:
            usr = User()
            
            # Set data ke objek
            usr.name = nama_baru
            usr.username = user_baru
            usr.password = pass_baru # Logic update password ada di method update()
            usr.posisi = posisi_baru
            
            # Panggil method update
            if usr.update(self.current_id):
                QMessageBox.information(self, "Sukses", "Data berhasil diperbarui!")
                self.reset_form(reset_id=True)
            else:
                QMessageBox.warning(self, "Gagal", "Gagal mengupdate data.")
                
        except Exception as e:
            QMessageBox.critical(self, "Error", str(e))

    def reset_form(self, reset_id=True):
        if reset_id:
            self.ui.lineEdit.clear()
            self.current_id = None
        self.ui.lineEdit_2.clear()
        self.ui.lineEdit_3.clear()
        self.ui.lineEdit_4.clear()
        self.ui.comboBox.setCurrentIndex(0)

# =================================================================
# MAIN PROGRAM
# =================================================================
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = EditUserForm()
    window.show()
    sys.exit(app.exec_())