# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-

# --- ANTI-CRASH: WAJIB DI BARIS PALING ATAS ---
import mysql.connector 

# Kita bungkus try-except agar ketahuan kalau ada file yang hilang
try:
    from dashboard_admin import DashboardAdminForm
    from dashboard_gudang import DashboardGudangForm
    from dasboard_kasir import DashboardKasirForm 
except ImportError as e:
    print(f"!!! CRASH SAAT IMPORT DASHBOARD !!!\nPenyebab: {e}")
    # Jangan exit, biarkan program jalan supaya kita bisa lihat errornya
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# --- IMPORT DASHBOARD DENGAN PENGAMAN ---

class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        
        # Judul
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 40, 600, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setText("SISTEM DEALER MOBIL SAMSUL JAYA")
        
        # Label & Input Username
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 150, 100, 20))
        self.label_2.setText("Username")
        self.input_username = QtWidgets.QLineEdit(Dialog)
        self.input_username.setGeometry(QtCore.QRect(350, 150, 200, 30))
        
        # Label & Input Password
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(250, 200, 100, 20))
        self.label_3.setText("Password")
        self.input_password = QtWidgets.QLineEdit(Dialog)
        self.input_password.setGeometry(QtCore.QRect(350, 200, 200, 30))
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password) 
        
        # Tombol Login
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setGeometry(QtCore.QRect(265, 260, 111, 35))
        self.btn_login.setText("Login")
        self.btn_login.setStyleSheet("background-color: #4CAF50; color: white; font-weight: bold;")
        
        # Tombol Keluar
        self.btn_exit = QtWidgets.QPushButton(Dialog)
        self.btn_exit.setGeometry(QtCore.QRect(435, 260, 111, 35))
        self.btn_exit.setText("Keluar")
        self.btn_exit.setStyleSheet("background-color: #f44336; color: white; font-weight: bold;")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setWindowTitle("Login System")

class LoginForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Login()
        self.ui.setupUi(self)
        
        # Event Listener
        self.ui.btn_login.clicked.connect(self.cek_login)
        self.ui.btn_exit.clicked.connect(self.close)

    def cek_login(self):
        user = self.ui.input_username.text()
        pwd = self.ui.input_password.text()

        if not user or not pwd:
            QMessageBox.warning(self, "Peringatan", "Username dan Password harus diisi!")
            return

        try:
            from connection import koneksi  
            mydb, cursor = koneksi()

            if mydb is None:
                QMessageBox.critical(self, "Error Database", "Gagal terhubung ke database!")
                return
            
            # Cek User (User: user, Kolom: posisi)
            query = "SELECT posisi FROM users WHERE username = %s AND password = %s"
            cursor.execute(query, (user, pwd))
            result = cursor.fetchone()
            
            if result:
                role = result[0].lower() # Admin -> admin
                
                QMessageBox.information(self, "Berhasil", f"Login Berhasil sebagai {role.upper()}")
                
                self.hide()
                self.dashboard = None
                
                # --- PENGAMANAN BUKA DASHBOARD ---
                try:
                    if role == "admin":
                        self.dashboard = DashboardAdminForm()
                    elif role == "gudang":
                        self.dashboard = DashboardGudangForm()
                    elif role == "kasir":
                        self.dashboard = DashboardKasirForm()
                    else:
                        QMessageBox.warning(self, "Error", f"Posisi '{role}' tidak dikenali!")
                        self.show()
                        return

                    # TAMPILKAN DASHBOARD
                    self.dashboard.exec_()
                
                except Exception as e:
                    # INI AKAN MUNCUL JIKA FILE DASHBOARD ERROR (Misal file insert belum ada)
                    print(f"Error Buka Dashboard: {e}")
                    QMessageBox.critical(self, "Gagal Membuka Menu", 
                        f"Gagal membuka menu {role}.\nKemungkinan ada file form yang belum dibuat.\n\nError: {e}")
                
                # Reset Form setelah logout/error
                self.ui.input_username.clear()
                self.ui.input_password.clear()
                self.show()
                
            else:
                QMessageBox.critical(self, "Gagal", "Username atau Password Salah!")

            if cursor: cursor.close()
            if mydb: mydb.close()

        except Exception as err:
            QMessageBox.critical(self, "Error System", f"Terjadi kesalahan: {err}")
                 
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = LoginForm()
    window.show()
    sys.exit(app.exec_())