# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

import sys
import warnings
warnings.filterwarnings("ignore")

# Import Backend
from mobil import Mobil, Mobil_Sport, Mobil_Listrik
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


# =================================================================
# 1. BAGIAN UI (TATA LETAK DIRAPIKAN)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 420) # Diperpanjang ke bawah agar muat
        
        # --- JUDUL ---
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # --- AREA PENCARIAN (Row 1) ---
        # Label "ID Barang"
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 70, 25))
        font_label = QtGui.QFont()
        font_label.setPointSize(10)
        self.label_2.setFont(font_label)
        self.label_2.setObjectName("label_2")
        
        # Input ID
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(110, 70, 150, 25))
        self.lineEdit.setObjectName("lineEdit")
        
        # Tombol Cari
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 70, 80, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        
        # --- AREA DETAIL BARANG (Row 2 - dst) ---
        # Garis Pemisah (Visual saja, pakai Frame)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 110, 320, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        # Label Kategori
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 130, 300, 25))
        self.label_6.setFont(font_label)
        self.label_6.setObjectName("label_6")
        
        # Label Nama
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 300, 25))
        self.label_4.setFont(font_label)
        self.label_4.setObjectName("label_4")
        
        # Label Harga
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 300, 25))
        self.label_5.setFont(font_label)
        self.label_5.setObjectName("label_5")
        
        # Label Stok
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 300, 25))
        self.label_3.setFont(font_label)
        self.label_3.setObjectName("label_3")
        
        # --- TOMBOL DELETE (Paling Bawah) ---
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 330, 200, 40))
        self.pushButton.setObjectName("pushButton")
        
        # Styling Tombol Delete (Merah & Tebal)
        self.pushButton.setStyleSheet("""
            QPushButton {
                background-color: #ff4d4d; 
                color: white; 
                font-weight: bold; 
                font-size: 14px;
                border-radius: 5px;
            }
            QPushButton:hover {
                background-color: #ff0000;
            }
        """)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hapus Barang"))
        self.label.setText(_translate("Dialog", "HAPUS BARANG"))
        self.label_2.setText(_translate("Dialog", "ID       "))
        self.pushButton_2.setText(_translate("Dialog", "Cari"))
        self.label_6.setText(_translate("Dialog", "Kategori: -"))
        self.label_4.setText(_translate("Dialog", "Merk: -"))
        self.label_5.setText(_translate("Dialog", "Harga: -"))
        self.label_3.setText(_translate("Dialog", "Stok: -"))
        self.pushButton.setText(_translate("Dialog", "HAPUS PERMANEN"))

# =================================================================
# 2. BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class DeleteBarangForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.current_id = None
        self.current_type = None 
        
        # Label Spesifikasi Khusus (Dinamis)
        # Diletakkan di bawah Stok (y=250)
        self.label_spek = QtWidgets.QLabel(self)
        self.label_spek.setGeometry(QtCore.QRect(50, 250, 300, 25))
        font_label = QtGui.QFont()
        font_label.setPointSize(10)
        self.label_spek.setFont(font_label)
        self.label_spek.setText("")
        
        self.setup_logika()

    def setup_logika(self):
        self.ui.lineEdit.setPlaceholderText("Masukkan ID")
        self.ui.pushButton_2.clicked.connect(self.aksi_cari)
        self.ui.pushButton.clicked.connect(self.aksi_hapus)

    def aksi_cari(self):
        uid = self.ui.lineEdit.text()
        if not uid:
            QMessageBox.warning(self, "Info", "Masukkan ID dulu!")
            return

        try:
            # 1. Cek Mobil Sport
            mobil = Mobil_Sport.get_by_id(uid)
            if mobil:
                self.tampilkan_data(mobil, "Mobil Sport", f"Kecepatan : {mobil.kecepatan} km/h")
                self.current_type = "sport"
                return

            # 2. Cek Mobil Listrik
            mobil = Mobil_Listrik.get_by_id(uid)
            if mobil:
                self.tampilkan_data(mobil, "Mobil Listrik", f"Kapasitas : {mobil.kapasitas} kWh")
                self.current_type = "listrik"
                return

            # 3. Cek Mobil Umum
            mobil = Mobil.get_by_id(uid)
            if mobil:
                self.tampilkan_data(mobil, "Mobil Umum", "Spesifikasi : -")
                self.current_type = "umum"
                return

            # Gak ketemu
            QMessageBox.warning(self, "404", "Barang tidak ditemukan.")
            self.reset_label()

        except Exception as e:
            QMessageBox.critical(self, "Error", str(e))

    def tampilkan_data(self, mobil, kategori, spek_text):
        self.current_id = str(mobil.id)
        self.ui.label_6.setText(f"Kategori : {kategori}")
        self.ui.label_4.setText(f"Merk     : {mobil.merk}")
        self.ui.label_5.setText(f"Harga    : Rp {mobil.harga:,}")
        self.ui.label_3.setText(f"Stok     : {mobil.stok} Unit")
        self.label_spek.setText(spek_text)
        QMessageBox.information(self, "Ketemu", "Data ditemukan.\nPastikan data benar sebelum menghapus.")

    def aksi_hapus(self):
        if not self.current_id:
            QMessageBox.warning(self, "Stop", "Cari barang dulu!")
            return

        tanya = QMessageBox.question(self, "Konfirmasi Hapus", 
            f"PERINGATAN!\n\nApakah Anda yakin ingin menghapus permanen:\n"
            f"ID: {self.current_id}\n"
            f"Merk: {self.ui.label_4.text().replace('Merk     : ', '')}?",
            QMessageBox.Yes | QMessageBox.No)
        
        if tanya == QMessageBox.Yes:
            try:
                sukses = False
                if self.current_type == "sport":
                    sukses = Mobil_Sport.hapus_by_id(self.current_id)
                elif self.current_type == "listrik":
                    sukses = Mobil_Listrik.hapus_by_id(self.current_id)
                elif self.current_type == "umum":
                    sukses = Mobil.hapus_by_id(self.current_id)
                
                if sukses:
                    QMessageBox.information(self, "Sukses", "Barang berhasil dihapus.")
                    self.reset_label()
                    self.ui.lineEdit.clear()
                else:
                    QMessageBox.warning(self, "Gagal", "Gagal menghapus.")

            except Exception as e:
                QMessageBox.critical(self, "Error", str(e))

    def reset_label(self):
        self.current_id = None
        self.current_type = None
        self.ui.label_6.setText("Kategori : -")
        self.ui.label_4.setText("Merk     : -")
        self.ui.label_5.setText("Harga    : -")
        self.ui.label_3.setText("Stok     : -")
        self.label_spek.setText("")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = DeleteBarangForm()
    window.show()
    sys.exit(app.exec_())