# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

import sys
import warnings
warnings.filterwarnings("ignore") # Sembunyikan warning merah

from user import User
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# =================================================================
# BAGIAN UI (JANGAN DIUBAH - SESUAI DESAIN KAMU)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        
        # Judul
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Input ID
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 30, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 80, 110, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("ID User")
        
        # Tombol Cari
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 80, 50, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        
        # Label Data (Nama, Username, dll)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(80, 110, 250, 20))
        self.label_5.setObjectName("label_5")
        
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 250, 20))
        self.label_3.setObjectName("label_3")
        
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(80, 170, 250, 20))
        self.label_6.setObjectName("label_6")
        
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(80, 200, 250, 20))
        self.label_8.setObjectName("label_8")
        
        # Tombol Delete
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(220, 250, 100, 35))
        self.pushButton.setObjectName("pushButton")
        


        #  TOMBOL BATAL
        self.btnBatal = QtWidgets.QPushButton(Dialog)
        self.btnBatal.setGeometry(QtCore.QRect(100, 250, 100, 35))
        self.btnBatal.setText("Batal")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hapus User"))
        self.label.setText(_translate("Dialog", "Hapus User"))
        self.label_2.setText(_translate("Dialog", "ID"))
        self.pushButton_2.setText(_translate("Dialog", "Cari"))
        self.label_5.setText(_translate("Dialog", "Nama: -"))
        self.label_3.setText(_translate("Dialog", "Username: -"))
        self.label_6.setText(_translate("Dialog", "Password: -"))
        self.label_8.setText(_translate("Dialog", "Posisi: -"))
        self.pushButton.setText(_translate("Dialog", "Hapus"))

# =================================================================
# BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class DeleteUserForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.current_id = None # Menyimpan ID yang ditemukan

        # Hubungkan Tombol
        self.ui.pushButton_2.clicked.connect(self.aksi_cari)   # Cari
        self.ui.pushButton.clicked.connect(self.aksi_hapus)    # Hapus

    def aksi_cari(self):
        id_input = self.ui.lineEdit.text().strip()
        if not id_input:
            QMessageBox.warning(self, "Peringatan", "Masukkan ID User dulu!")
            return

        try:
            usr = User()
            # Panggil method select_user_by_id dari user.py
            data = usr.select_user_by_id(id_input)
            
            if data:
                # Data ditemukan: (id, name, username, password, posisi)
                self.current_id = data[0]
                
                # Tampilkan ke Label
                self.ui.label_5.setText(f"Nama: {data[1]}")
                self.ui.label_3.setText(f"Username: {data[2]}")
                self.ui.label_6.setText(f"Password: {data[3]}") 
                self.ui.label_8.setText(f"Posisi: {data[4]}")
                
                QMessageBox.information(self, "Ketemu", "User ditemukan! Klik HAPUS jika yakin.")
            else:
                QMessageBox.warning(self, "404", "User tidak ditemukan.")
                self.reset_label()

        except Exception as e:
            QMessageBox.critical(self, "Error", str(e))

    def aksi_hapus(self):
        # 1. Cek apakah sudah cari user?
        if not self.current_id:
            QMessageBox.warning(self, "Stop", "Cari user dulu sebelum menghapus!")
            return

        # 2. Konfirmasi (Penting untuk Delete!)
        konfirmasi = QMessageBox.question(
            self, "Konfirmasi Hapus", 
            "Apakah Anda yakin ingin menghapus user ini secara permanen?",
            QMessageBox.Yes | QMessageBox.No
        )

        if konfirmasi == QMessageBox.Yes:
            try:
                usr = User()
                # Panggil method hapus dari user.py
                if usr.hapus(self.current_id):
                    QMessageBox.information(self, "Sukses", "User berhasil dihapus!")
                    self.reset_form()
                else:
                    QMessageBox.warning(self, "Gagal", "Gagal menghapus user.")
            except Exception as e:
                QMessageBox.critical(self, "Error", str(e))

    def reset_label(self):
        self.current_id = None
        self.ui.label_5.setText("Nama: -")
        self.ui.label_3.setText("Username: -")
        self.ui.label_6.setText("Password: -")
        self.ui.label_8.setText("Posisi: -")

    def reset_form(self):
        self.ui.lineEdit.clear()
        self.reset_label()

# =================================================================
# MAIN PROGRAM
# =================================================================
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = DeleteUserForm()
    window.show()
    sys.exit(app.exec_())