# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_edit_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

import sys
import warnings
warnings.filterwarnings("ignore")

# Import Backend
from mobil import Mobil, Mobil_Sport, Mobil_Listrik
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


# =================================================================
# 1. BAGIAN UI (TATA LETAK DIRAPIKAN)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 480) # Diperpanjang ke bawah agar muat semua
        
        # --- JUDUL ---
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # --- AREA PENCARIAN (Row 1) ---
        # Label ID
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 70, 25))
        font_label = QtGui.QFont()
        font_label.setPointSize(8)
        self.label_2.setFont(font_label)
        self.label_2.setObjectName("label_2")
        
        # Input ID
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 70, 150, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Masukkan ID")
        
        # Tombol Cari
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 70, 80, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        
        # --- GARIS PEMISAH ---
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 110, 320, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        # --- AREA EDIT DATA (Row 2 dst) ---
        
        # 1. MERK
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 140, 80, 25))
        self.label_4.setFont(font_label)
        self.label_4.setObjectName("label_4")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 140, 230, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")

        # 2. STOK
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 80, 25))
        self.label_3.setFont(font_label)
        self.label_3.setObjectName("label_3")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 180, 230, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")

        # 3. HARGA
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 220, 80, 25))
        self.label_5.setFont(font_label)
        self.label_5.setObjectName("label_5")
        
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 220, 230, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")

        # 4. KATEGORI
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 260, 80, 25))
        self.label_6.setFont(font_label)
        self.label_6.setObjectName("label_6")
        
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 260, 230, 25))
        self.comboBox.setObjectName("comboBox")

        # --- TOMBOL UPDATE (Paling Bawah) ---
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 380, 200, 40))
        self.pushButton.setObjectName("pushButton")
        
        # Style Tombol Update (Biru)
        self.pushButton.setStyleSheet("""
            QPushButton {
                background-color: #007acc; 
                color: white; 
                font-weight: bold; 
                font-size: 14px;
                border-radius: 5px;
            }
            QPushButton:hover {
                background-color: #005c99;
            }
        """)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit Barang"))
        self.label.setText(_translate("Dialog", "EDIT DATA BARANG"))
        self.label_2.setText(_translate("Dialog", "ID Barang"))
        self.pushButton_2.setText(_translate("Dialog", "Cari"))
        self.label_4.setText(_translate("Dialog", "Merk"))
        self.label_3.setText(_translate("Dialog", "Stok"))
        self.label_5.setText(_translate("Dialog", "Harga"))
        self.label_6.setText(_translate("Dialog", "Kategori"))
        self.pushButton.setText(_translate("Dialog", "SIMPAN PERUBAHAN"))

# =================================================================
# 2. BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class EditBarangForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.current_id = None
        
        # --- UI DINAMIS: Input Spesifikasi ---
        # Ditempatkan di bawah Kategori (y=300)
        self.label_spek = QtWidgets.QLabel(self)
        self.label_spek.setGeometry(QtCore.QRect(40, 300, 90, 25))
        font_label = QtGui.QFont()
        font_label.setPointSize(8)
        self.label_spek.setFont(font_label)
        self.label_spek.setText("Spesifikasi")
        
        self.lineEdit_spek = QtWidgets.QLineEdit(self)
        self.lineEdit_spek.setGeometry(QtCore.QRect(130, 300, 230, 25))
        self.lineEdit_spek.setPlaceholderText("Kecepatan / Kapasitas")
        
        # Setup Logika
        self.setup_logika()

    def setup_logika(self):
        # Isi ComboBox
        self.ui.comboBox.clear()
        self.ui.comboBox.addItems(["Mobil Umum", "Mobil Sport", "Mobil Listrik"])
        self.ui.comboBox.setEnabled(False) # Kategori dikunci saat edit agar aman
        
        # Hubungkan Tombol
        self.ui.pushButton_2.clicked.connect(self.aksi_cari)   # Cari
        self.ui.pushButton.clicked.connect(self.aksi_update)   # Update

    def aksi_cari(self):
        uid = self.ui.lineEdit.text()
        if not uid:
            QMessageBox.warning(self, "Warning", "Masukkan ID dulu!")
            return
        
        try:
            # 1. Cek di Mobil Sport
            mobil = Mobil_Sport.get_by_id(uid)
            if mobil:
                self.populate_form(mobil, "Mobil Sport", str(mobil.kecepatan))
                self.label_spek.setText("Kecepatan")
                self.lineEdit_spek.setPlaceholderText("km/h")
                self.lineEdit_spek.setEnabled(True)
                self.current_id = uid
                return

            # 2. Cek di Mobil Listrik
            mobil = Mobil_Listrik.get_by_id(uid)
            if mobil:
                self.populate_form(mobil, "Mobil Listrik", str(mobil.kapasitas))
                self.label_spek.setText("Kapasitas")
                self.lineEdit_spek.setPlaceholderText("kWh")
                self.lineEdit_spek.setEnabled(True)
                self.current_id = uid
                return

            # 3. Cek di Mobil Umum
            mobil = Mobil.get_by_id(uid)
            if mobil:
                self.populate_form(mobil, "Mobil Umum", "-")
                self.label_spek.setText("Spek (-)")
                self.lineEdit_spek.setPlaceholderText("Tidak ada")
                self.lineEdit_spek.setEnabled(False) # Umum gak punya spek
                self.current_id = uid
                return

            # Gak ketemu
            QMessageBox.warning(self, "404", "ID tidak ditemukan di database.")
            self.reset_form()

        except Exception as e:
            QMessageBox.critical(self, "Error", str(e))

    def populate_form(self, mobil, kategori, spek_val):
        self.ui.lineEdit_2.setText(mobil.merk)
        self.ui.lineEdit_3.setText(str(mobil.stok))
        self.ui.lineEdit_4.setText(str(mobil.harga))
        self.ui.comboBox.setCurrentText(kategori)
        self.lineEdit_spek.setText(spek_val)
        QMessageBox.information(self, "Ketemu", f"Data Ditemukan:\n{mobil.merk} ({kategori})")

    def aksi_update(self):
        if not self.current_id:
            QMessageBox.warning(self, "Stop", "Cari barang dulu!")
            return

        merk = self.ui.lineEdit_2.text()
        stok = self.ui.lineEdit_3.text()
        harga = self.ui.lineEdit_4.text()
        spek = self.lineEdit_spek.text()
        kategori = self.ui.comboBox.currentText()

        try:
            # Update sesuai kategori
            if kategori == "Mobil Sport":
                m = Mobil_Sport(merk, int(harga), int(stok), int(spek))
                m.update_by_id(self.current_id)
            elif kategori == "Mobil Listrik":
                m = Mobil_Listrik(merk, int(harga), int(stok), int(spek))
                m.update_by_id(self.current_id)
            else: # Mobil Umum
                m = Mobil(merk, int(harga), int(stok))
                m.update_by_id(self.current_id)
            
            QMessageBox.information(self, "Sukses", "Data berhasil diperbarui!")
            self.reset_form()
            self.ui.lineEdit.clear() # Clear ID juga

        except ValueError:
            QMessageBox.warning(self, "Error", "Harga/Stok/Spek harus berupa angka!")
        except Exception as e:
            QMessageBox.critical(self, "Error", str(e))

    def reset_form(self):
        self.current_id = None
        self.ui.lineEdit_2.clear()
        self.ui.lineEdit_3.clear()
        self.ui.lineEdit_4.clear()
        self.lineEdit_spek.clear()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = EditBarangForm()
    window.show()
    sys.exit(app.exec_())