# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_view_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

import sys
import warnings
warnings.filterwarnings("ignore") # Sembunyikan warning

from user import User
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QHeaderView

# Import Backend

# =================================================================
# BAGIAN UI (JANGAN DIUBAH)
# =================================================================
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 350) # Sedikit diperlebar biar tabel muat
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 350, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Tabel
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(20, 70, 410, 250))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Daftar User"))
        self.label.setText(_translate("Dialog", "Data User Terdaftar"))

# =================================================================
# BAGIAN LOGIKA (CONTROLLER)
# =================================================================
class ViewUserForm(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        
        # Panggil fungsi untuk load data begitu jendela dibuka
        self.load_data()

    def load_data(self):
        try:
            usr = User()
            # Ambil semua data user dari database
            # Pastikan method select_all_users() ada di user.py
            data_users = usr.select_all_users()
            
            # Buat Model untuk Tabel
            model = QStandardItemModel()
            # Set Header (Judul Kolom)
            model.setHorizontalHeaderLabels(['ID', 'Nama', 'Username', 'Posisi'])

            # Masukkan data baris per baris
            for row in data_users:
                # row[0]=id, row[1]=name, row[2]=username, row[3]=posisi
                item_id = QStandardItem(str(row[0]))
                item_nama = QStandardItem(row[1])
                item_user = QStandardItem(row[2])
                item_posisi = QStandardItem(row[3])
                
                # Agar data tidak bisa diedit langsung di tabel (Read Only)
                item_id.setEditable(False)
                item_nama.setEditable(False)
                item_user.setEditable(False)
                item_posisi.setEditable(False)

                model.appendRow([item_id, item_nama, item_user, item_posisi])

            # Pasang model ke TableView
            self.ui.tableView.setModel(model)
            
            # Rapikan Lebar Kolom (Agar memenuhi tabel)
            header = self.ui.tableView.horizontalHeader()
            header.setSectionResizeMode(QHeaderView.Stretch)

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", f"Gagal memuat data: {e}")

# =================================================================
# MAIN PROGRAM
# =================================================================
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = ViewUserForm()
    window.show()
    sys.exit(app.exec_())